package mx.gob.imss.fepac.autorizacion.Enums;

public enum EnumRoles {
	
	ROLE_ADMINISTRADOR_DEL_SISTEMA_CUMAE(10,"ROLE_ADMINISTRADOR_DEL_SISTEMA(CUMAE)"),
	ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_UNIDAD_ESPECIAL(11,"ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_UNIDAD_ESPECIAL(UMAE)"),
	ROLE_DIRECTIVO_DE_DELEGACION(12,"ROLE_DIRECTIVO_DE_DELEGACION"),
	ROLE_DIRECTIVO_DE_UNIDAD(13,"ROLE_DIRECTIVO_DE_UNIDAD"),
	ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_ALMACEN_DELEGACIONAL(3,"ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_ALMACEN DELEGACIONAL"),
	ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_UNIDAD(4,"ROLE_ADMINISTRADOR_DEL_SISTEMA_EN_UNIDAD_(COBCIR)"),
	ROLE_MEDICO_AUTORIZADO_PARA_EXPEDIR_OCI(5,"ROLE_MEDICO_AUTORIZADO_PARA_EXPEDIR OCI"),
	ROLE_SISTEMA_TRAMITADOR_DE_FOLIOS(6,"ROLE_SISTEMA_TRAMITADOR_DE_FOLIOS"),
	ROLE_SISTEMA_RECEPTOR_DE_FOLIOS	(7,"ROLE_SISTEMA_RECEPTOR_DE_FOLIOS"),
	ROLE_SISTEMA_HIBRIDO(8,"ROLE_SISTEMA_HIBRIDO"),
	ROLE_ADMINISTRADOR_DEL_SISTEMA_TOTAL (1,"ROLE_ADMINISTRADOR_DEL_SISTEMA_TOTAL"),
	ROLE_SECCIÓN_DELEGACIONAL_DE_CONTROL_DE_RECETARIOS(2,"ROLE_SECCIÓN_DELEGACIONAL_DE_CONTROL_DE_RECETARIOS(SEDECOR)"),
	ROLE_ADMINISTRADOR_DEL_SISTEMA(9,"ROLE_ADMINISTRADOR_DEL_SISTEMA")
	;
	
	private Long code;
	private String description;

	EnumRoles(long code, String description)
	{
		this.code = code;
		this.description = description;

	}

	public Long getCode()
	{
		return this.code;
	}

	public String getDescription()
	{
		return this.description;
	}
}
